# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0617b854d187d0937067011db86809272d274eb8ae7d8aa9ef663faacd1e2aa7ca00fcfa1666d77b6d978ad1c8fd25ad20faf4a52a3f2eb4eb0c25467fae1972

test:
  secret_key_base: 24c721d5eef81260c0fa43c90dd0d33406c3ff7374311b065822f819502f5ba9d14a03dd88cbaeb9a1d0dfa8c5334ecdd0cf95d6ba999f7cf83474e0be9bd4ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
